name: CI/CD for Static Website

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run HTML Linter
        run: |
          sudo apt-get install -y npm
          npm install -g htmlhint
          htmlhint ./**/*.html

      - name: Run CSS Linter
        run: |
          npm install -g stylelint
          stylelint '**/*.css'

  deploy:
    runs-on: ubuntu-latest
    needs: lint  # Only run after lint job is complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The directory containing your static site files
